on: 
  push:
    branches:
      - main
name: ğŸš€ Enviando arquivos...
jobs:
  web-deploy:
    name: ğŸ‰ ComeÃ§ando!
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Pegando os cÃ³digos mais recentes
      uses: actions/checkout@v2
    
    - name: ğŸ“‚ Enviando via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: public_html/
        local-dir: build/